{
 "title": "q3",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Insurance Plan",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>\nMonthly Plan: {{last}}\n</h1>"
   },
   "targets": [
    {
     "measurement": "starinsurance",
     "select": [
      [
       { "params": [ "insurance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "demo",
     "select": [
      [
       { "params": [ "Engine" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "speed",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Person Entered Car",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "measurement": "images",
     "select": [
      [
       { "params": [ "binary" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License Points Check",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": {
    "content": "<h1>Points: \n{{last}} &star;\n</h1>\n"
   },
   "targets": [
    {
     "measurement": "starinsurance",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Authorized Attempts ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "demo",
     "query": "SELECT \"UNAUTH\" FROM (SELECT count(\"UnAuthorized\") AS \"UNAUTH\" FROM \"demo\" WHERE $timeFilter and UnAuthorized=0  GROUP BY time(1h) ) WHERE \"UNAUTH\">0",
     "select": [
      [
       { "params": [ "UnAuthorized" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Car Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "measurement": "demo",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ],
      [
       { "params": [ "lon" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Times Slept ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DM1",
     "query": "SELECT count(\"slept\") FROM (SELECT count(\"sleep-driving\") AS \"slept\" FROM \"DM1\" WHERE $timeFilter GROUP BY time(1h)) WHERE \"slept\">0",
     "select": [
      [
       { "params": [ "sleep-driving" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "slept" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Times Crossed Speed Limit",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "speed",
     "query": "SELECT count(\"avg\") FROM (SELECT mean(\"speed\") AS \"avg\" FROM \"speed\" WHERE $timeFilter GROUP BY time(5m)) WHERE \"avg\">40",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}